trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build_and_deploy
  displayName: Build image and deploy on prem
  jobs:
  - job: Build_and_Push
    displayName: Build and Push
    pool: rpi-cluster
    steps:
    - task: Docker@2
      displayName: build and push agent
      inputs:
        containerRegistry: 'dockerhub_mactat'
        repository: 'mactat/map-pacer-agent'
        command: 'buildAndPush'
        Dockerfile: 'agent/Dockerfile'
        buildContext: '.'
        tags: 'arm-latest'
    - task: Docker@2
      displayName: build and push map-service
      inputs:
        containerRegistry: 'dockerhub_mactat'
        repository: 'mactat/map-pacer-map-service'
        command: 'buildAndPush'
        Dockerfile: 'map-service/Dockerfile'
        buildContext: '.'
        tags: 'arm-latest'
  - job: Deploy
    dependsOn:
    - Build_and_Push
    displayName: Deploy on prem
    pool:
       name: rpi-cluster
       demands:
        - agent.name -equals pi4-rpios-1
    steps:
    - checkout: self
    - bash: |
        sudo docker stack up map-pacer --compose-file docker-swarm.yml
        sudo docker service update map-pacer_agent --image mactat/map-pacer-agent:arm-latest --force
        sudo docker service update map-pacer_map-service --image mactat/map-pacer-map-service:arm-latest --force


