trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build  
  displayName: Build image
  jobs:
  - job: Build_and_Push
    displayName: Build and Push
    pool: rpi-cluster
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerhub_mactat'
        repository: 'mactat/map-pacer-agent'
        command: 'buildAndPush'
        Dockerfile: 'agent/Dockerfile'
        buildContext: '.'
        tags: 'arm-latest'
     - task: Docker@2
      inputs:
        containerRegistry: 'dockerhub_mactat'
        repository: 'mactat/map-pacer-map-service'
        command: 'buildAndPush'
        Dockerfile: 'map-service/Dockerfile'
        buildContext: '.'
        tags: 'arm-latest'
