trigger: none
pr: none

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'


strategy:
  matrix:
    'low_resources_profile':
      limits_cpu: "0.50"
      reservation_cpu: "0.25"
      limit_memory: "128M"
      reservation_memory: "256M"
    'medium_resources_profile':
      limits_cpu: "0.50"
      reservation_cpu: "0.25"
      limit_memory: "128M"
      reservation_memory: "256M"
    'high_resources_profile':
      limits_cpu: "0.50"
      reservation_cpu: "0.25"
      limit_memory: "128M"
      reservation_memory: "256M"

stages:
- stage: Build_and_deploy
  displayName: Build image and deploy on prem
  jobs:
  - job: Deploy
    dependsOn:
    displayName: Deploy on prem
    pool:
       name: rpi-cluster
       demands:
        - agent.name -equals pi4-rpios-1
    steps:
    - checkout: self
    - bash: |
       echo "test"
      displayName: Change parameters in yamls
    - bash: |
        sudo docker stack up map-pacer --compose-file docker-swarm.yml
        sudo docker service update map-pacer_agent --image mactat/map-pacer-agent:arm-latest --force
        sudo docker service update map-pacer_map-service --image mactat/map-pacer-map-service:arm-latest --force
      displayName: "Deploy adjusted services mem: ${ reservation_memory } cpu: ${ reservation_cpu }"
  - job: Test
    dependsOn:
    - Deploy
    displayName: "Performance test for mem: ${ reservation_memory } cpu: ${ reservation_cpu }"
    steps:
    - checkout: self
    - task: Kubernetes@1
      displayName: Login to k8s cluster
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'okteto-cloud-connection'
        command: login
    - bash: |
        mkdir cpu_$(reservation_cpu)_mem_$(reservation_memory)
        make performance SYSTEM_ID="on_prem" FLAGS="--json > cpu_$(reservation_cpu)_mem_$(reservation_memory)/res.json"
      displayName: "Performance test for mem: ${ reservation_memory } cpu: ${ reservation_cpu }"



