apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mosquitto.fullname" . }}
  annotations:
    dev.okteto.com/generate-host: "true"
spec:
  rules:
  - http:
      paths:
      - path: /mqtt
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ include "mosquitto.fullname" . }}
            port:
              number: {{ .Values.ports.websocket.port }}