apiVersion: apps/v1
kind: Deployment
metadata:
  name: map-service-foreign
  labels:
    app: map-service-foreign
spec:
  replicas: 1
  selector:
    matchLabels:
      app: map-service-foreign
  template:
    metadata:
      labels:
        app: map-service-foreign
    spec:
      containers:
      - name: map-service-foreign
        image: mactat/map-pacer-map-service:latest
        ports:
        - containerPort: 8888
        env:
        - name: AGENTS_NUMBER
          value: "3"
        - name: BROKER_HOSTNAME
          value: "broker-service"
        - name: BROKER_PORT
          value: "1883"
        - name: CLOUD_BROKER_HOSTNAME
          value: "cloud-broker"
        - name: CLOUD_BROKER_PORT
          value: "9001" 
        - name: SYSTEM_ID
          value: "foreign_system"
        - name: TLS
          value: "false"
