{
 "title": "Core dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Agent Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "agent_state{agent_state=\"running\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Leader",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (leader{leader=\"yes\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Avg memory usage per agent[b]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(container) (container_memory_usage_bytes{container=\"agent\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Agent count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(container) (agent_state{agent_state=\"running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg CPU per pod",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(container) (rate(container_cpu_usage_seconds_total{container=\"agent\"}[$__rate_interval])) / 0.15",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Single path measurements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Time of single path calculation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(single_path_compute_sum[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total time of single path calculation",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "single_path_compute_sum", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Path calculated",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (single_path_compute_count)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}