apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-agent
  labels:
    app: cloud-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-agent
  template:
    metadata:
      labels:
        app: cloud-agent
    spec:
      containers:
      - name: cloud-agent
        image: mactat/map-pacer-cloud-agent:latest
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-agent-service
spec:
  selector:
    app.kubernetes.io/name: cloud-agent
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloud-agent-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cloud-agent-service
            port:
              number: 8888