apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-agent
  labels:
    app: cloud-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-agent
  template:
    metadata:
      labels:
        app: cloud-agent
    spec:
      containers:
      - name: cloud-agent
        image: mactat/map-pacer-cloud-agent:latest
        ports:
        - containerPort: 8888
        env:
        - name: CLOUD_BROKER_HOSTNAME
          value: "cloud-broker-service"
        - name: CLOUD_BROKER_PORT
          value: "1883" 
        # - name: CLOUD_BROKER_HOSTNAME
        #   value: "tcp-mo2.mogenius.io"
        # - name: CLOUD_BROKER_PORT
        #   value: "10106"
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-agent
spec:
  selector:
    app: cloud-agent
  ports:
    - port: 80
      targetPort: 8888
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloud-agent
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /cloud-agent
        pathType: ImplementationSpecific
        backend:
          service:
            name: cloud-agent
            port:
              number: 80