apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: agent
  labels:
    app: agent
spec:
  replicas: 3
  serviceName: agent
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      containers:
      - name: agent
        image: mactat/map-pacer-agent:latest
        resources:
          limits:
            memory: "0.6Gi"
            cpu: "300m"  
          requests:
            memory: "0.2Gi"
            cpu: "150m"  
        env:
        - name: AGENTS_NUMBER
          value: "3"
        - name: BROKER_HOSTNAME
          value: "broker-service"
        - name: BROKER_PORT
          value: "1883"
        - name: CLOUD_BROKER_HOSTNAME
          value: "tcp-mo2.mogenius.io"
        - name: CLOUD_BROKER_PORT
          value: "10106"
