apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: agent-statefullset
  labels:
    app: agent
spec:
  replicas: 3
  serviceName: agent
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      containers:
      - name: agent
        image: mactat/map-pacer-agent:latest
        env:
        - name: AGENTS_NUMBER
          value: "3"
        - name: BROKER_HOSTNAME
          value: "broker-service"
