apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
  labels:
        app: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
      - name: broker-container
        image: hivemq/hivemq-ce
        ports:
        - containerPort: 1883

---
apiVersion: v1
kind: Service
metadata:
  name: broker-service
spec:
  selector:
    app: broker 
  ports:
  - port: 1883
    targetPort: 1883