name: CI/CD

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dockerhub
    steps:
    - uses: actions/checkout@v3
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        envkey_DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        file_name: .env
        fail_on_empty: true
    - name: Build and Push Docker image
      run: make cloud-build
  deploy:
    runs-on: ubuntu-latest
    environment: okteto-cloud
    needs: build
    steps:
    - uses: actions/checkout@v3
    - uses: azure/k8s-set-context@v2
      with:
         method: kubeconfig
         kubeconfig: ${{ secrets.KUBECONFIG_OKTETO }}
         namespace: mactat
    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.10.0
    - name: Deploy Cloud Services
      run: |
        kubectl config set-context --current --namespace=mactat
        helm upgrade -i cloud-broker ./cloud-broker
        CLOUD_SERVICES="cloud-agent database backend frontend performance-test"
        for service in $CLOUD_SERVICES
        do
          echo "Deploying ${service}"
          kubectl apply -f ./$service/kubernetes.yaml
          kubectl rollout restart deployment $service
        done
    - name: Deploy Local Services
      run: |
        kubectl config set-context --current --namespace=local-mactat
        LOCAL_SERVICES="broker map-service"
        for service in $LOCAL_SERVICES
        do
          echo "Deploying ${service}"
          kubectl apply -f ./$service/kubernetes.yaml
          kubectl rollout restart deployment $service
        done
        kubectl apply -f ./agent/kubernetes.yaml
        kubectl rollout restart statefulset agent