name: CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dockerhub
    steps:
    - uses: actions/checkout@v3
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        envkey_DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        file_name: .env
        fail_on_empty: true
    - name: Build and Push Docker image
      run: make cloud-build
  deploy:
    runs-on: ubuntu-latest
    environment: okteto-cloud
    needs: build
    steps:
    - uses: actions/checkout@v3
    - uses: azure/k8s-set-context@v2
      with:
         method: kubeconfig
         kubeconfig: ${{ secrets.KUBECONFIG_OKTETO }}
         namespace: mactat
    - name: Deploy
      run: |
        CLOUD_SERVICES="cloud-agent backend frontend" #cloud broker is not changing for now
        for service in $CLOUD_SERVICES
        do
          echo "Deploying ${service}"
          kubectl apply -f ./$service/kubernetes.yaml
          kubectl rollout restart deployment $service
        done
