---
name: "thesis-release"

on:
  push:
    tags:
      - "vt*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: "Build & export"
        run: |
          touch .env #Should be filled with secret creds
          make pdf
      - name: Set release name
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: Thesis release version ${{ env.RELEASE_VERSION }}
          automatic_release_tag: ${{ env.RELEASE_VERSION }}
          files: |
            ./docs/thesis/Thesis.pdf